"""add defaults to run

Revision ID: a4421c217bea
Revises: a57d4ab02e08
Create Date: 2026-07-21 21:10:19.986733

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "a4421c217bea"
down_revision: Union[str, Sequence[str], None] = "a57d4ab02e08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
