"""Public configuration and domain types for portfolio snapshot workflows."""

from genai_template.workflow.portfolio import inspect_snapshot
from genai_template.workflow.portfolio.adapters.repositories import (
    LocalGitSnapshotReader,
)
from genai_template.workflow.portfolio.config import (
    GenerationConfig,
    GenerationInputLimits,
    GenerationLocations,
    InferenceConfig,
    LocalGitRepositoryConfig,
    PortfolioConfig,
    ProjectConfig,
    ProjectDocumentContextConfig,
    SelectionConfig,
    StructuredGenerationConfig,
    SummaryUnitConfig,
    TokenPricingConfig,
    load_portfolio_config,
)
from genai_template.workflow.portfolio.domain import (
    ArtifactProvenance,
    ArtifactRunReport,
    CachedArtifact,
    CommittedRepositoryEntry,
    CorpusBuild,
    CorpusManifest,
    GenerationRequest,
    GenerationResult,
    GenerationRunReport,
    ManifestDocument,
    ManifestPrompt,
    ProviderAuditMetadata,
    RenderedDocument,
    RepositoryReadError,
    RepositoryReadResult,
    RepositorySnapshot,
    SnapshotFile,
    StepRunReport,
    SummaryPlan,
    SummaryUnitPlan,
    TokenUsage,
)
from genai_template.workflow.portfolio.ports import RepositoryReader
from genai_template.workflow.portfolio.snapshot import (
    SnapshotSelectionError,
    SummaryPlanningError,
    build_repository_snapshot,
    build_summary_plan,
)

__all__ = [
    "ArtifactProvenance",
    "ArtifactRunReport",
    "CachedArtifact",
    "CommittedRepositoryEntry",
    "CorpusBuild",
    "CorpusManifest",
    "GenerationConfig",
    "GenerationInputLimits",
    "GenerationLocations",
    "GenerationRequest",
    "GenerationResult",
    "GenerationRunReport",
    "InferenceConfig",
    "LocalGitRepositoryConfig",
    "LocalGitSnapshotReader",
    "ManifestDocument",
    "ManifestPrompt",
    "PortfolioConfig",
    "ProjectConfig",
    "ProjectDocumentContextConfig",
    "ProviderAuditMetadata",
    "RenderedDocument",
    "RepositoryReadError",
    "RepositoryReadResult",
    "RepositoryReader",
    "RepositorySnapshot",
    "SelectionConfig",
    "SnapshotFile",
    "SnapshotSelectionError",
    "StepRunReport",
    "StructuredGenerationConfig",
    "SummaryPlan",
    "SummaryPlanningError",
    "SummaryUnitConfig",
    "SummaryUnitPlan",
    "TokenPricingConfig",
    "TokenUsage",
    "build_repository_snapshot",
    "build_summary_plan",
    "inspect_snapshot",
    "load_portfolio_config",
]
