"""Pydantic schemas representing canonical document chunks."""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class DocumentChunk(BaseModel):
    """Represents a canonical chunk flowing through the RAG pipeline.

    A ``DocumentChunk`` is the central data structure exchanged between
    pipeline components. It is intentionally framework-agnostic and
    independent from LlamaIndex's internal ``Node`` representation.

    Attributes:
        id:
            Unique identifier of the chunk.
        document_id:
            Identifier of the parent document.
        text:
            Chunk text.
        metadata:
            Arbitrary metadata associated with the chunk.
        embedding:
            Dense embedding generated by an embedding model.
            This field is populated after the embedding stage.
    """

    model_config = ConfigDict(
        extra="forbid",
        validate_assignment=True,
    )

    id: str = Field(..., description="Unique chunk identifier.")

    document_id: str = Field(
        ...,
        description="Parent document identifier.",
    )

    text: str = Field(
        ...,
        min_length=1,
        description="Chunk text.",
    )

    metadata: dict[str, Any] = Field(
        default_factory=dict,
        description="Chunk metadata.",
    )

    embedding: list[float] | None = Field(
        default=None,
        description="Optional embedding vector.",
    )
